development:
  host: localhost
  database: socialprice_development
  allow_dynamic_fields: false

test:
  host: localhost
  database: socialprice_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
# production:
#   host: <%= ENV['MONGOID_HOST'] %>
#   port: <%= ENV['MONGOID_PORT'] %>
#   username: <%= ENV['MONGOID_USERNAME'] %>
#   password: <%= ENV['MONGOID_PASSWORD'] %>
#   database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
# 

# Staging environment
staging:
  uri: <%= ENV['MONGOLAB_URI'] %>